{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_milliseconds_total{source=\"jwt-pizza-service-dev\", key=\"endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pizzas_total{source=\"jwt-pizza-service-dev\", key=\"sold\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pizzas_total{source=\"jwt-pizza-service-dev\", key=\"fail\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizzas_total{source=\"jwt-pizza-service-dev\", key=\"revenue\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_milliseconds_total{source=\"jwt-pizza-service-dev\", key=\"creation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "authentication_total{key=\"active\", source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(authentication_total{key=\"success\", source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(authentication_total{key=\"fail\", source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service-dev\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(requests_total{key=\"get\", source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(requests_total{key=\"put\", source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(requests_total{key=\"delete\", source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(requests_total{key=\"post\", source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}